(function () {
  "use strict";
  const { React } = window.LITTLE_DAYS_RUNTIME;
  const { useRef, useState, useLayoutEffect } = React;
  const h = React.createElement;
  const marker = "__little_days_rich_v1__\n";
  const escape = text => text.replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;").replace(/"/g, "&quot;");

  // Only formatting generated by this editor may enter the editable DOM.
  function clean(html) {
    const doc = new DOMParser().parseFromString(html, "text/html");
    function copy(node) {
      if (node.nodeType === 3) return escape(node.textContent);
      if (node.nodeType !== 1) return "";
      const tag = node.tagName.toLowerCase();
      if (["script", "style", "iframe", "object", "svg", "math"].includes(tag)) return "";
      if (tag === "input") return node.type === "checkbox" ? `<input type="checkbox" contenteditable="false" aria-label="待办方框"${node.hasAttribute("checked") ? " checked" : ""}>` : "";
      if (tag === "br") return "<br>";
      const children = [...node.childNodes].map(copy).join("");
      if (!["b", "strong", "u", "s", "strike", "i", "em", "span", "font", "div", "p", "ul", "ol", "li"].includes(tag)) return children;
      const color = node.style.color || (tag === "font" ? node.getAttribute("color") : "");
      const safeColor = /^(#[\da-f]{3,8}|rgba?\([\d\s.,%]+\)|[a-z]+)$/i.test(color || "") ? color : "";
      const outTag = tag === "font" ? "span" : tag;
      return `<${outTag}${safeColor ? ` style="color:${safeColor}"` : ""}>${children}</${outTag}>`;
    }
    return [...doc.body.childNodes].map(copy).join("");
  }
  function initialHTML(value) {
    if (value.startsWith(marker)) return clean(value.slice(marker.length));
    return value.split("\n").map(line => {
      let html = escape(line)
        .replace(/\*\*(.+?)\*\*/g, "<strong>$1</strong>")
        .replace(/~~(.+?)~~/g, "<s>$1</s>")
        .replace(/&lt;u&gt;(.+?)&lt;\/u&gt;/g, "<u>$1</u>")
        .replace(/&lt;span style=&quot;color:(#[\da-fA-F]{6})&quot;&gt;(.+?)&lt;\/span&gt;/g, '<span style="color:$1">$2</span>');
      html = html.replace(/^(?:- )?\[([ xX]?)\]\s?/, (_, state) => `<input type="checkbox" contenteditable="false" aria-label="待办方框"${state.toLowerCase() === "x" ? " checked" : ""}> `);
      if (/^[-*] /.test(html)) html = `<ul><li>${html.slice(2)}</li></ul>`;
      else if (/^\d+\. /.test(html)) html = `<ol><li>${html.replace(/^\d+\. /, "")}</li></ol>`;
      return `<div>${html || "<br>"}</div>`;
    }).join("");
  }
  function ProjectEditor({ value, onChange, disabled }) {
    const ref = useRef(null);
    const range = useRef(null);
    const composing = useRef(false);
    const history = useRef([]);
    const position = useRef(-1);
    const lastValue = useRef(value);
    const [color, setColor] = useState("#687d55");
    const [historyState, setHistoryState] = useState({ undo: false, redo: false });
    function remember() {
      const selection = window.getSelection();
      if (selection.rangeCount && ref.current.contains(selection.anchorNode) && ref.current.contains(selection.focusNode)) range.current = selection.getRangeAt(0).cloneRange();
    }
    function path(node) {
      const result = [];
      while (node && node !== ref.current) { result.unshift([...node.parentNode.childNodes].indexOf(node)); node = node.parentNode; }
      return result;
    }
    function bookmark() {
      remember();
      const r = range.current;
      return r && ref.current.contains(r.startContainer) ? { start: path(r.startContainer), end: path(r.endContainer), a: r.startOffset, b: r.endOffset } : null;
    }
    function restore(mark) {
      ref.current.focus();
      const r = document.createRange();
      try {
        const resolve = parts => parts.reduce((node, index) => node.childNodes[index], ref.current);
        if (mark) { r.setStart(resolve(mark.start), mark.a); r.setEnd(resolve(mark.end), mark.b); }
        else { r.selectNodeContents(ref.current); r.collapse(false); }
      } catch { r.selectNodeContents(ref.current); r.collapse(false); }
      const selection = window.getSelection(); selection.removeAllRanges(); selection.addRange(r); range.current = r.cloneRange();
    }
    function sync() {
      ref.current.querySelectorAll('input[type="checkbox"]').forEach(box => box.toggleAttribute("checked", box.checked));
      const html = clean(ref.current.innerHTML);
      const next = marker + html;
      lastValue.current = next;
      onChange(next);
    }
    function push() {
      const entry = { html: ref.current.innerHTML, mark: bookmark() };
      if (history.current[position.current]?.html !== entry.html) {
        history.current = history.current.slice(0, position.current + 1);
        history.current.push(entry);
        if (history.current.length > 150) history.current.shift();
        position.current = history.current.length - 1;
      } else history.current[position.current].mark = entry.mark;
      setHistoryState({ undo: position.current > 0, redo: position.current < history.current.length - 1 });
    }
    function travel(step) {
      const next = position.current + step;
      if (next < 0 || next >= history.current.length) return;
      position.current = next;
      const entry = history.current[next];
      ref.current.innerHTML = entry.html;
      restore(entry.mark); sync();
      setHistoryState({ undo: next > 0, redo: next < history.current.length - 1 });
    }
    useLayoutEffect(() => {
      ref.current.innerHTML = initialHTML(value);
      history.current = [{ html: ref.current.innerHTML, mark: null }]; position.current = 0;
    }, []);
    // Parent updates normally echo our own value. External replacements reset history.
    useLayoutEffect(() => {
      if (value !== lastValue.current) {
        ref.current.innerHTML = initialHTML(value); lastValue.current = value;
        history.current = [{ html: ref.current.innerHTML, mark: null }]; position.current = 0;
        setHistoryState({ undo: false, redo: false });
      }
    }, [value]);
    function focusSelection() {
      remember();
      ref.current.focus();
      const selection = window.getSelection();
      if (range.current && ref.current.contains(range.current.startContainer)) { selection.removeAllRanges(); selection.addRange(range.current); }
      else restore(null);
    }
    function insertBox() {
      document.execCommand("insertHTML", false, '<input type="checkbox" contenteditable="false" aria-label="待办方框">&nbsp;');
    }
    function autoBox() {
      const selection = window.getSelection();
      if (!selection.isCollapsed || selection.anchorNode?.nodeType !== 3) return;
      const node = selection.anchorNode, end = selection.anchorOffset;
      const match = /(?:- )?\[(?: )?\]$/.exec(node.textContent.slice(0, end));
      if (!match) return;
      const r = document.createRange(); r.setStart(node, end - match[0].length); r.setEnd(node, end);
      selection.removeAllRanges(); selection.addRange(r); insertBox();
    }
    function autoMarkdown() {
      const selection = window.getSelection();
      if (!selection.isCollapsed || selection.anchorNode?.nodeType !== 3) return;
      const node = selection.anchorNode, end = selection.anchorOffset;
      const before = node.textContent.slice(0, end);
      const inline = /(?:\*\*([^*\n]+)\*\*|~~([^~\n]+)~~)$/.exec(before);
      const list = /^(?:- |\* |1\. )$/.test(before) && node === node.parentNode.firstChild;
      if (!inline && !list) return;
      const r = document.createRange(); r.setStart(node, inline ? end - inline[0].length : 0); r.setEnd(node, end);
      selection.removeAllRanges(); selection.addRange(r);
      if (inline) {
        const tag = inline[1] ? "b" : "s";
        document.execCommand("insertHTML", false, `<${tag}>${escape(inline[1] || inline[2])}</${tag}>`);
      } else {
        document.execCommand("delete");
        document.execCommand(before.startsWith("1") ? "insertOrderedList" : "insertUnorderedList");
      }
    }
    function input() {
      if (composing.current) return;
      push(); autoBox(); autoMarkdown(); push(); sync();
    }
    function command(name, arg) {
      if (disabled) return;
      focusSelection(); push();
      if (name === "check") insertBox();
      else document.execCommand(name, false, arg);
      remember(); push(); sync();
    }
    function keydown(event) {
      if (composing.current || event.isComposing) return;
      if (event.ctrlKey || event.metaKey) {
        const key = event.key.toLowerCase();
        if (key === "z" || key === "y") { event.preventDefault(); travel(key === "y" || event.shiftKey ? 1 : -1); }
        else if (key === "b" || key === "u") { event.preventDefault(); command(key === "b" ? "bold" : "underline"); }
      }
    }
    return h("div", { className: "project-editor" },
      h("div", { ref, className: "rich-project-body", role: "textbox", "aria-label": "项目进展", "aria-multiline": true,
        contentEditable: !disabled, suppressContentEditableWarning: true, "data-placeholder": "写下目前的进展、想法和下一步…",
        onInput: input, onKeyDown: keydown, onKeyUp: remember, onMouseUp: remember, onBlur: remember,
        onCompositionStart: () => { composing.current = true; }, onCompositionEnd: () => { composing.current = false; input(); },
        onPaste: event => { event.preventDefault(); command("insertText", event.clipboardData.getData("text/plain")); },
        onDrop: event => event.preventDefault(),
        onClick: event => { if (event.target.matches('input[type="checkbox"]')) { if (disabled) { event.preventDefault(); return; } event.target.toggleAttribute("checked", event.target.checked); push(); sync(); } }
      }),
      h("div", { className: "format-toolbar", role: "group", "aria-label": "正文格式" },
        [["bold", "B", "加粗"], ["underline", "U", "下划线"], ["strikeThrough", "S", "删除线"], ["insertUnorderedList", "☷", "无序列表"], ["insertOrderedList", "1.", "有序列表"], ["check", "☐", "待办方框"]].map(([name, label, title]) =>
          h("button", { key: name, type: "button", className: `format-${name}`, title, "aria-label": title, disabled,
            onMouseDown: event => event.preventDefault(), onClick: () => command(name) }, label)),
        h("label", { className: "format-color", title: "文字颜色", style: { borderColor: color } }, "A",
          h("select", { "aria-label": "文字颜色", value: "", disabled,
            onChange: event => { setColor(event.target.value); command("foreColor", event.target.value); } },
            h("option", { value: "", disabled: true }, "文字颜色"),
            [["#687d55", "苔绿"], ["#b34e4e", "砖红"], ["#476f9b", "雾蓝"], ["#89649e", "浅紫"], ["#a87825", "赭黄"], ["#444444", "深灰"]].map(([value, name]) => h("option", { key: value, value }, name)))),
        h("button", { type: "button", title: "撤销 Ctrl+Z", "aria-label": "撤销", disabled: disabled || !historyState.undo, onMouseDown: e => e.preventDefault(), onClick: () => travel(-1) }, "↶"),
        h("button", { type: "button", title: "重做 Ctrl+Shift+Z", "aria-label": "重做", disabled: disabled || !historyState.redo, onMouseDown: e => e.preventDefault(), onClick: () => travel(1) }, "↷")));
  }
  window.LITTLE_DAYS_PROJECT_EDITOR = ProjectEditor;
})();
